# parameters

## SERVO NUMBER INDEX
SERVO_BOTTOM = 0
SERVO_LEFT = 1
SERVO_RIGHT = 2
SERVO_HAND = 3

## CALIBRATION FLAG
CONFIRM_FLAG = 0x80
CALIBRATION_FLAG = 10
CALIBRATION_LINEAR_FLAG = 11
CALIBRATION_SERVO_FLAG = 12
CALIBRATION_STRETCH_FLAG = 13

## OFFSET EEPROM ADDRESS
LINEAR_INTERCEPT_START_ADDRESS = 70
LINEAR_SLOPE_START_ADDRESS = 50
OFFSET_START_ADDRESS = 30
OFFSET_STRETCH_START_ADDRESS = 20

SERIAL_NUMBER_ADDRESS = 100

## EEPROM DATA TYPE INDEX
EEPROM_DATA_TYPE_BYTE = 1
EEPROM_DATA_TYPE_INTEGER = 2
EEPROM_DATA_TYPE_FLOAT = 4

## PROTOCOL MESSAGE
READY = "[READY]"
SET_MOVE = "sMovX{}Y{}Z{}V{}"
SIMULATION = "gSimX{}Y{}Z{}"
GET_VERSION = "gVer"
SET_ANGLE = "sAngN{}V{}"
SET_RAW_ANGLE = "sSerN{}V{}"
SET_PUMP = "sPumV{}"
GET_PUMP = "gPum"
SET_GRIPPER = "sGriV{}"
GET_GRIPPER = "gGri"
ATTACH_SERVO = "sAttN{}"
DETACH_SERVO = "sDetN{}"
GET_COOR = "gCrd"
GET_ANGLE = "gAng"
GET_RAW_ANGLE = "gSer"
GET_IS_MOVE = "gMov"
GET_TIP = "gTip"
SET_BUZZER = "sBuzF{}T{}"
SET_POLAR = "sPolS{}R{}H{}V{}"
GET_POLAR = "gPol"
GET_EEPROM = "gEEPA{}T{}"
SET_EEPROM = "sEEPA{}T{}V{}"
GET_ANALOG = "gAnaN{}"
GET_DIGITAL = "gDigN{}"